server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos del frontend (React compilado)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Redirige todas las rutas al index.html para que React Router maneje la navegación
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso: redirige las llamadas /api/* al contenedor del backend
    location /api/ {
        proxy_pass https://eduflix-production.up.railway.app/api/;
        proxy_ssl_server_name on;
    }

}
